stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: tagbiopy:branch-${CICD_GIT_BRANCH}
      pushRemote: true
      registry: platform-write-registry.dev.tag.bio
- name: trigger-downstream-pipelines
  steps:
  - runScriptConfig:
      image: platform-registry.dev.tag.bio/tagbio-ci-pipeline:branch-master
      shellScript: $TAGBIO_CI_PIPELINE_DIR/trigger-pipelines.js
    env:
      TRIGGER_PIPELINES_BRANCH: master
      TRIGGER_PIPELINES_REPO_FILTER: "/tagbio-fc-jars.git$"
    envFrom:
    - sourceName: rancher-api
      sourceKey: RANCHER_ACCESS_KEY
    - sourceName: rancher-api
      sourceKey: RANCHER_BASE_URL
    - sourceName: rancher-api
      sourceKey: RANCHER_CLUSTER_ID
    - sourceName: rancher-api
      sourceKey: RANCHER_PROJECT_ID
    - sourceName: rancher-api
      sourceKey: RANCHER_SECRET_KEY
  - runScriptConfig:
      image: platform-registry.dev.tag.bio/tagbio-ci-pipeline:branch-master
      shellScript: $TAGBIO_CI_PIPELINE_DIR/trigger-pipelines.js
    env:
      TRIGGER_PIPELINES_BRANCH: stage
      TRIGGER_PIPELINES_REPO_FILTER: "/tagbio-fc-jars.git$"
    envFrom:
    - sourceName: rancher-api
      sourceKey: RANCHER_ACCESS_KEY
    - sourceName: rancher-api
      sourceKey: RANCHER_BASE_URL
    - sourceName: rancher-api
      sourceKey: RANCHER_CLUSTER_ID
    - sourceName: rancher-api
      sourceKey: RANCHER_PROJECT_ID
    - sourceName: rancher-api
      sourceKey: RANCHER_SECRET_KEY
timeout: 60
notification:
  recipients:
  - notifier: c-78zdm:n-6n6m4
  - notifier: c-589tr:n-2245x
  condition:
  - Failed