dependencies:
  - numpy
  - python
  - pip
  - pandas
  - pyarrow
  - plotly
  - requests
  - inflection
  - ipywidgets
  - lifelines
  - matplotlib
  - openpyxl
  - pytest
  - python-duckdb
  - pyyaml
  - papermill
  - ipykernel
  - seaborn
  - setuptools
  - setuptools_scm
  - tabulate
  - wheel
  - xlsxwriter
