name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas==2.0.2
  - plotly==5.15.0
  - pytypes==1.0b9
  - requests==2.31.0
  - inflection==0.5.1
  - pyyaml==6.0
  - papermill==2.3.4
  - ipykernel==6.23.3

