dependencies:
  - numpy
  - python
  - pip
  - pandas
  - plotly
  - requests
  - inflection
  - matplotlib
  - pyyaml
  - papermill
  - ipykernel
  - seaborn
  - setuptools
  - setuptools_scm
  - wheel