#!/usr/bin/env python3

import argparse
import json

from typing import Dict

from tagbiopy import logger, __version__
from tagbiopy.protocol import load_function, TagbioData, TagbioResult
from tagbiopy.utils import create_temp_file, now, print_ts
from tagbiopy.protocol import RunFunction


def parse_arguments() -> argparse.Namespace:
    usage: Dict[str, str] = {
        'fc_data': 'JSON file specifying FC and protocol. Generated by FC.',
        'user_function': 'User function passed in a py file.',
        'output_file': 'Path to the output file.',
        'output_type': 'File type of result.'
    }

    parser = argparse.ArgumentParser()

    parser.add_argument('-d', '--fc_data', required=True, help=usage['fc_data'])
    parser.add_argument('-f', '--user_function', required=True, help=usage['user_function'])
    parser.add_argument('-t', '--output_type', required=False, help=usage['output_type'])
    parser.add_argument('-o', '--output_file', required=False, help=usage['output_file'])

    args = parser.parse_args()

    return args


def set_extension_and_path(args: argparse.Namespace) -> (str, str):
    extension = args.output_type
    path = args.output_file

    if path is None:
        path = create_temp_file(prefix='py_{}_'.format(now('_')), suffix='.temp')

    if extension is not None:
        if path.endswith('.temp'):
            path = path.replace('.temp', extension)
    return extension, path


def run_jupyter_notebook(args):
    pass


def run_python_function(args):
    # Initialize tag_data
    logger.info('Initialize TagbioData')
    tag_data = TagbioData(args.fc_data)

    logger.debug(f'Check fc_packet: {tag_data.fc_packet = }')

    logger.info(f'Check TagbioData.df ... ')
    if tag_data.df is None:
        logger.info('No data requested')
    else:
        logger.info(f'{tag_data.df.columns = }')

    # Initialize tag_result. If output path is a temp file
    logger.info('Initialize TagbioResult')
    extension, path = set_extension_and_path(args)
    tag_result = TagbioResult(extension=extension, path=args.output_file)

    # Load user function from python script
    logger.info(f'Load user function from {args.user_function}')
    user_function = load_function(args)

    # Execute user function
    logger.info(f'Execute user function {user_function!r}')
    user_function(tag_data, tag_result)


def run():
    print_ts(f'tagbiopy {__version__}', flush=True)
    args = parse_arguments()

    msg = f'Python command line arguments:\n{json.dumps(vars(args), indent=2)}'
    logger.info(msg)
    print_ts(msg, flush=True)

    # if args.user_function.endswith('.py'):
    #     run_python_function(args)
    # elif args.user_function.endswith('.ipynb'):
    #     # run_jupyter_notebook(args)
    #     pass
    # else:
    #     msg = f'Illegal input: {args.user_function!r} should either be a python script or a jupyter notebook.'
    #     logger.exception(msg)
    #     raise RuntimeError(msg)

    RunFunction(args)()

    logger.info('Done')
    print_ts('Done', flush=True)


def main():
    try:
        run()
    except Exception as e:
        logger.exception(e)
        raise
